# Recommended install command: (can substitute conda for mamba)
# mamba env create -p ./.venv --file conda.dev.env.yaml
name:
channels:
  - conda-forge # location for more needed packages
  - fastai # location of nbdev libraries
  - bioconda # location of most bioinformatic tools
dependencies:
  - python=3.10
  - ca-certificates
  - openssl
  - ipykernel # for integration with notebooks
  - nbdev # Using nbdev framework
  - pip # for installing python packages
  - pip:
    - quarto # used in nbdev for doc generation
  - jupyterlab # used by quarto
  - pandas # used by quarto
  - matplotlib # used by quarto for plotting
  - gh # used in nbdev for doc generation and github integration
  - twine # for pypi deployments
  - anaconda-client # for anaconda deployments
  - conda-build # for conda deployments
# Standard libraries used in our code development
  - python-dotenv # for loading environment variables from .env file
  - pip:
    - envyaml # for loading environment variables into variables with a .yaml file
# Additional programs for specific development follow